name: camerav1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image: ^4.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
